---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rtreesitter

<!-- badges: start -->
<!-- badges: end -->

rtreesitter provides R bindings to the [tree-sitter](https://tree-sitter.github.io/tree-sitter/) parsing library.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
remotes::install_github("jimhester/rtreesitter")
```

## Usage

```bash
mkdir vendor
cd vendor
git clone https://github.com/jimhester/tree-sitter-r
git clone https://github.com/tree-sitter/tree-sitter-python
git clone https://github.com/tree-sitter/tree-sitter-javascript
git clone https://github.com/tree-sitter/tree-sitter-go
```

```{r}
pkgload::load_all("~/p/rtreesitter")

build_library("build/my-languages.so",
  c("vendor/tree-sitter-r",
    "vendor/tree-sitter-python",
    "vendor/tree-sitter-javascript",
    "vendor/tree-sitter-go")
)

p_r <- parser_new("tree_sitter_R")
tree_sexp(parser_parse(p_r, "x <- function(x) 1"))

p_py <- parser_new("tree_sitter_python")
tree_sexp(parser_parse(p_py,
"
def foo():
    if bar:
       baz()
"))


p_go <- parser_new("tree_sitter_go")

tree_sexp(parser_parse(p_go,
'package main
import "fmt"
func main() {
    fmt.Println("hello world")
}'))

p_js <- parser_new("tree_sitter_javascript")
tree_sexp(parser_parse(p_js, '
    let name = "world";
    alert("hello " + name);'))
```
