# Generated by cpp11: do not edit by hand

parser_new <- function(language) {
  .Call("_rtreesitter_parser_new", language, PACKAGE = "rtreesitter")
}

parser_parse <- function(p, code) {
  .Call("_rtreesitter_parser_parse", p, code, PACKAGE = "rtreesitter")
}

tree_sexp <- function(t) {
  .Call("_rtreesitter_tree_sexp", t, PACKAGE = "rtreesitter")
}
